name: clippy
channels:
  - anaconda
  - bioconda
  - r
  - bcbio
  - defaults
dependencies:
  - bedtools=2.26.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - numpydoc=1.1.0
  - pandas=1.0.5
  - pybedtools=0.8.1
  - scipy=1.5.0
