name: clippy
channels:
  - anaconda
  - conda-forge
  - bioconda
  - r
  - bcbio
  - defaults
dependencies:
  - python=3.7
  - bedtools=2.26.0
  - numpy
  - numpy-base
  - numpydoc
  - pandas
  - pybedtools
  - scipy
  - matplotlib
  - pytest
  - pytest-cov
