name: clippy
channels:
  - anaconda
  - conda-forge
  - bioconda
  - r
  - bcbio
  - defaults
dependencies:
  - python=3.8
  - bedtools=2.26.0
  - numpy
  - numpy-base
  - numpydoc
  - pandas
  - pybedtools
  - scipy
  - matplotlib
  - dash=1.20.0
  - dash-bootstrap-components=0.11.3
  # Testing
  - pytest
  - pytest-cov
  - bs4
  - percy
  - pytest-selenium
  - python-chromedriver-binary
  - pytest-profiling
  - graphviz